### ISSUE TITLE
空文件夹时报错或者默认没有 pictures文件夹

### ISSUE THREAD

**Issue by qq978304139** [qq978304139/AutoPlayPhoto#2]
01-21 08:22:14.347 I/ActivityManager(  482): Start proc wii.image.autoplay for activity wii.image.autoplay/.PlayPhoto: pid=4091 uid=10067 gids={50067, 9997, 1028, 1015, 3003} abi=armeabi-v7a
01-21 08:22:14.559 E/PlayPhoto( 4091): SettingItemPlaySleep:3
01-21 08:22:14.563 I/PlayPhoto( 4091):       pathString    /sdcard/pictures
01-21 08:22:14.570 I/PlayPhoto( 4091): photo list
01-21 08:22:14.571 I/PlayPhoto( 4091):    no  photo 
01-21 08:22:14.571 I/PlayPhoto( 4091): music list
01-21 08:22:14.571 I/PlayPhoto( 4091):    no  music 
01-21 08:22:14.575 E/PlayPhoto( 4091): =======onResume()
01-21 08:22:14.606 I/ActivityManager(  482): START u0 {flg=0x4000000 cmp=wii.image.autoplay/.ImageEyesActivity} from uid 10067 on display 0
01-21 08:22:14.621 E/PlayPhoto( 4091):  -----PLAYNEXTONE ----- 
01-21 08:22:14.621 E/PlayPhoto( 4091): Playingindex:  0
01-21 08:22:14.622 D/AndroidRuntime( 4091): Shutting down VM
01-21 08:22:14.625 E/AndroidRuntime( 4091): FATAL EXCEPTION: main
01-21 08:22:14.625 E/AndroidRuntime( 4091): Process: wii.image.autoplay, PID: 4091
01-21 08:22:14.625 E/AndroidRuntime( 4091): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at java.util.ArrayList.get(ArrayList.java:308)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at wii.image.autoplay.PlayPhoto.ReloadFileUpdate(PlayPhoto.java:308)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at wii.image.autoplay.PlayPhoto$3.handleMessage(PlayPhoto.java:264)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at android.os.Looper.loop(Looper.java:135)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at java.lang.reflect.Method.invoke(Native Method)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-21 08:22:14.625 E/AndroidRuntime( 4091): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by qq978304139** [comment]
wii.image.autoplay.PlayPhoto.ReloadFileUpdate(PlayPhoto.java:308
修改后ok，不知有什么问题	
public void ReloadFileUpdate() {
		if(Playingindex == fileinfoList.size()){
			Playingindex = 0;
			return;
		}
